#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : PyYAML
Version  : 3.13
Release  : 47
URL      : https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Source0  : https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Summary  : YAML parser and emitter for Python
Group    : Development/Tools
License  : MIT
Requires: PyYAML-license = %{version}-%{release}
Requires: PyYAML-python = %{version}-%{release}
Requires: PyYAML-python3 = %{version}-%{release}
BuildRequires : Cython
BuildRequires : Cython-legacypython
BuildRequires : buildreq-distutils23
BuildRequires : buildreq-distutils3
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : yaml-dev
Patch1: 0001-CVE-2017-18342-1.patch
Patch2: 0002-CVE-2017-18342-2.patch

%description
and interaction with scripting languages.  PyYAML is a YAML parser
        and emitter for Python.
        
        PyYAML features a complete YAML 1.1 parser, Unicode support, pickle
        support, capable extension API, and sensible error messages.  PyYAML
        supports standard YAML tags and provides Python-specific tags that
        allow to represent an arbitrary Python object.
        
        PyYAML is applicable for a broad range of tasks from complex
        configuration files to object serialization and persistance.

%package legacypython
Summary: legacypython components for the PyYAML package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the PyYAML package.


%package license
Summary: license components for the PyYAML package.
Group: Default

%description license
license components for the PyYAML package.


%package python
Summary: python components for the PyYAML package.
Group: Default
Requires: PyYAML-python3 = %{version}-%{release}
Provides: pyyaml-python

%description python
python components for the PyYAML package.


%package python3
Summary: python3 components for the PyYAML package.
Group: Default
Requires: python3-core

%description python3
python3 components for the PyYAML package.


%prep
%setup -q -n PyYAML-3.13
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551413140
export LDFLAGS="${LDFLAGS} -fno-lto"
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python setup.py test || :
%install
export SOURCE_DATE_EPOCH=1551413140
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/PyYAML
cp LICENSE %{buildroot}/usr/share/package-licenses/PyYAML/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/PyYAML/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
